# IMAGE_HEIGHT = 512
# IMAGE_WIDTH = 512
IMAGE_HEIGHT = None
IMAGE_WIDTH = None
# IMAGE_HEIGHT = 1272
# IMAGE_WIDTH = 1920
IMAGES_SIZE = (IMAGE_HEIGHT, IMAGE_WIDTH)
IMAGES_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, 3)
