@echo off

:start
	set dbr=DataBlockRegister

	echo //======================================================================> %dbr%.hpp_test
	echo /*! \file DataBlockRegister.hpp>> %dbr%.hpp_test
	echo  *>> %dbr%.hpp_test
	echo  * \copydoc Copyright>> %dbr%.hpp_test
	echo  * \author Jan Christian Dittmer (jcd)>> %dbr%.hpp_test
	echo  * \date Feb 05, 2014>> %dbr%.hpp_test
	echo  *>> %dbr%.hpp_test
	echo  * This file has been automatically generated by>> %dbr%.hpp_test
	echo  * ibeosdk VS prebuild step.>> %dbr%.hpp_test
	echo  * Do not change it manually. All changes will be>> %dbr%.hpp_test
	echo  * lost the next time ibeosdk is compiled.>> %dbr%.hpp_test
	echo  *///------------------------------------------------------------------->> %dbr%.hpp_test

	echo. >> %dbr%.hpp_test

	echo #ifndef DATABLOCKREGISTER_HPP_SEEN>> %dbr%.hpp_test
	echo #define DATABLOCKREGISTER_HPP_SEEN>> %dbr%.hpp_test

	echo. >> %dbr%.hpp_test

	echo #ifdef _WIN32>> %dbr%.hpp_test
	for %%f in (datablocks\*.cpp) do call :action %%~nf
	echo #endif // _WIN32>> %dbr%.hpp_test

	echo. >> %dbr%.hpp_test

	echo #endif // DATABLOCKREGISTER_HPP_SEEN>> %dbr%.hpp_test

	if not exist %dbr%.hpp (
		echo Create new DataBlock register file.
		rename %dbr%.hpp_test %dbr%.hpp
		goto endloop
	) else (
		fc %dbr%.hpp %dbr%.hpp_test > nul
		if errorlevel 1 goto difffound
	)

	echo DataBlock register file is up to date.
	del %dbr%.hpp_test
	goto endloop


:difffound
	echo Replacing old DatabBlock register file.
	copy %dbr%.hpp_test %dbr%.hpp
	del %dbr%.hpp_test
	goto endloop


:action
	if %1 == DataBlock goto endloop
	if %1 == Command goto endloop
	
	echo   Found DataBlock %1. Add to register file.
	echo #pragma comment (linker, "/include:?registerId@?$RegisteredDataBlock@V%1@ibeosdk@@@ibeosdk@@0VDataBlockRegisterId@DataBlock@2@B")>> %dbr%.hpp_test

:endloop

